# Generated by Django 6.0.6 on 2026-07-08 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finch", "0002_subscription"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="finch",
            name="original",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reposts",
                to="finch.finch",
                verbose_name="Original post",
            ),
        ),
        migrations.AddField(
            model_name="finch",
            name="views_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Views"),
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("text", models.CharField(max_length=280, verbose_name="Comment")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Commented date")),
                ("finch", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="comments", to="finch.finch")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="comments", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
