# Generated by Codex on 2026-07-08

from django.db import migrations


def allow_notification_without_finch(apps, schema_editor):
    Notification = apps.get_model("finch", "Notification")
    new_field = Notification._meta.get_field("finch")
    old_field = new_field.clone()
    old_field.null = False
    old_field.blank = False
    old_field.set_attributes_from_name("finch")
    old_field.remote_field.model = new_field.remote_field.model

    schema_editor.alter_field(Notification, old_field, new_field, strict=True)


class Migration(migrations.Migration):

    dependencies = [
        ("finch", "0004_notification"),
    ]

    operations = [
        migrations.RunPython(allow_notification_without_finch, migrations.RunPython.noop),
    ]
