# Generated by Django 6.0.6 on 2026-07-10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("finch", "0006_finch_user_created_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="FinchView",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("viewer_id", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("finch", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="views", to="finch.finch")),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("finch", "viewer_id"), name="unique_finch_viewer_view"),
                ],
            },
        ),
    ]
