# Generated by Django 6.0.6 on 2026-07-10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("finch", "0007_finchview_unique_views"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("event_type", models.CharField(choices=[("login", "Login"), ("profile_share", "Profile share")], max_length=32)),
                ("path", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("target_user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="profile_share_events", to=settings.AUTH_USER_MODEL)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="platform_events", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["event_type", "-created_at"], name="plat_evt_type_created_idx"),
                    models.Index(fields=["user", "-created_at"], name="plat_evt_user_created_idx"),
                ],
            },
        ),
    ]
